## 
## -------------------------------------------------------------
##    Copyright 2008-2009 Mentor Graphics Corporation
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

VMM_HOME ?= ../../../..

run: test

test: 
	irun $(VMM_HOME)/sv/std_lib/vmm_str_dpi.c -incdir $(VMM_HOME)/sv test.sv -l test.log

clean:
	rm -rf INCA_libs test.log
