/*
 Copyright 2019 Alain Dargelas
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*  This file is automatically generated by generate_parser_listener.tcl
 *  DO NOT EDIT THIS FILE.
 *  If a method needs custom operator, write the method in SourceCompile/SV3_1aPpTreeShapeListener.cpp
*/

/* 
 * File:   SourceCompile/SV3_1aPpTreeShapeListener.h
 * Author: alain
 *
 * Created on April 16, 2017, 8:28 PM
 */

#ifndef SV3_1APPTREESHAPELISTENER_H
#define SV3_1APPTREESHAPELISTENER_H

#include <regex>

#include "SourceCompile/PreprocessFile.h"
#include "SourceCompile/CompileSourceFile.h"
#include "SourceCompile/Compiler.h"
#include "SourceCompile/SymbolTable.h"
#include "SourceCompile/CompilationUnit.h"
#include "Design/TimeInfo.h"
#include "SourceCompile/SV3_1aPpTreeListenerHelper.h"

namespace SURELOG {

    class SV3_1aPpTreeShapeListener : public SV3_1aPpParserBaseListener , public SV3_1aPpTreeListenerHelper {

	public:

	SV3_1aPpTreeShapeListener(PreprocessFile* pp, antlr4::CommonTokenStream* tokens, PreprocessFile::SpecialInstructions& instructions);


  virtual void enterTop_level_rule(SV3_1aPpParser::Top_level_ruleContext * /*ctx*/) override ;
  virtual void exitTop_level_rule(SV3_1aPpParser::Top_level_ruleContext * ctx) override { addVObject (ctx, VObjectType::slTop_level_rule); }
  virtual void enterSource_text(SV3_1aPpParser::Source_textContext * /*ctx*/) override ;
  virtual void exitSource_text(SV3_1aPpParser::Source_textContext * ctx) override { addVObject (ctx, VObjectType::slSource_text); }
  virtual void enterNull_rule(SV3_1aPpParser::Null_ruleContext * /*ctx*/) override { }
  virtual void exitNull_rule(SV3_1aPpParser::Null_ruleContext * ctx) override { addVObject (ctx, VObjectType::slNull_rule); }
  virtual void enterDescription(SV3_1aPpParser::DescriptionContext * /*ctx*/) override { }
  virtual void exitDescription(SV3_1aPpParser::DescriptionContext * /*ctx*/) override ;
  virtual void enterMacroInstanceWithArgs(SV3_1aPpParser::MacroInstanceWithArgsContext * /*ctx*/) override ;
  virtual void exitMacroInstanceWithArgs(SV3_1aPpParser::MacroInstanceWithArgsContext * /*ctx*/) override ;
  virtual void enterMacroInstanceNoArgs(SV3_1aPpParser::MacroInstanceNoArgsContext * /*ctx*/) override ;
  virtual void exitMacroInstanceNoArgs(SV3_1aPpParser::MacroInstanceNoArgsContext * ctx) override { addVObject (ctx, VObjectType::slMacroInstanceNoArgs); }
  virtual void enterUnterminated_string(SV3_1aPpParser::Unterminated_stringContext * /*ctx*/) override ;
  virtual void exitUnterminated_string(SV3_1aPpParser::Unterminated_stringContext * ctx) override { addVObject (ctx, VObjectType::slUnterminated_string); }
  virtual void enterMacro_actual_args(SV3_1aPpParser::Macro_actual_argsContext * /*ctx*/) override { }
  virtual void exitMacro_actual_args(SV3_1aPpParser::Macro_actual_argsContext * ctx) override { addVObject (ctx, VObjectType::slMacro_actual_args); }
  virtual void enterComments(SV3_1aPpParser::CommentsContext * /*ctx*/) override ;
  virtual void exitComments(SV3_1aPpParser::CommentsContext * /*ctx*/) override ;
  virtual void enterNumber(SV3_1aPpParser::NumberContext * /*ctx*/) override ;
  virtual void exitNumber(SV3_1aPpParser::NumberContext * /*ctx*/) override ;
  virtual void enterPound_delay(SV3_1aPpParser::Pound_delayContext * /*ctx*/) override { }
  virtual void exitPound_delay(SV3_1aPpParser::Pound_delayContext * ctx) override { addVObject (ctx, VObjectType::slPound_delay); }
  virtual void enterMacro_definition(SV3_1aPpParser::Macro_definitionContext * /*ctx*/) override { }
  virtual void exitMacro_definition(SV3_1aPpParser::Macro_definitionContext * ctx) override { addVObject (ctx, VObjectType::slMacro_definition); }
  virtual void enterInclude_directive(SV3_1aPpParser::Include_directiveContext * /*ctx*/) override ;
  virtual void exitInclude_directive(SV3_1aPpParser::Include_directiveContext * /*ctx*/) override ;
  virtual void enterLine_directive(SV3_1aPpParser::Line_directiveContext * /*ctx*/) override ;
  virtual void exitLine_directive(SV3_1aPpParser::Line_directiveContext * /*ctx*/) override ;
  virtual void enterDefault_nettype_directive(SV3_1aPpParser::Default_nettype_directiveContext * /*ctx*/) override ;
  virtual void exitDefault_nettype_directive(SV3_1aPpParser::Default_nettype_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDefault_nettype_directive); }
  virtual void enterSv_file_directive(SV3_1aPpParser::Sv_file_directiveContext * /*ctx*/) override ;
  virtual void exitSv_file_directive(SV3_1aPpParser::Sv_file_directiveContext * /*ctx*/) override ;
  virtual void enterSv_line_directive(SV3_1aPpParser::Sv_line_directiveContext * /*ctx*/) override ;
  virtual void exitSv_line_directive(SV3_1aPpParser::Sv_line_directiveContext * /*ctx*/) override ;
  virtual void enterTimescale_directive(SV3_1aPpParser::Timescale_directiveContext * /*ctx*/) override ;
  virtual void exitTimescale_directive(SV3_1aPpParser::Timescale_directiveContext * ctx) override { addVObject (ctx, VObjectType::slTimescale_directive); }
  virtual void enterUndef_directive(SV3_1aPpParser::Undef_directiveContext * /*ctx*/) override ;
  virtual void exitUndef_directive(SV3_1aPpParser::Undef_directiveContext * ctx) override { addVObject (ctx, VObjectType::slUndef_directive); }
  virtual void enterIfdef_directive(SV3_1aPpParser::Ifdef_directiveContext * /*ctx*/) override ;
  virtual void exitIfdef_directive(SV3_1aPpParser::Ifdef_directiveContext * ctx) override { addVObject (ctx, VObjectType::slIfdef_directive); }
  virtual void enterIfdef_directive_in_macro_body(SV3_1aPpParser::Ifdef_directive_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitIfdef_directive_in_macro_body(SV3_1aPpParser::Ifdef_directive_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slIfdef_directive_in_macro_body); }
  virtual void enterIfndef_directive(SV3_1aPpParser::Ifndef_directiveContext * /*ctx*/) override ;
  virtual void exitIfndef_directive(SV3_1aPpParser::Ifndef_directiveContext * ctx) override { addVObject (ctx, VObjectType::slIfndef_directive); }
  virtual void enterIfndef_directive_in_macro_body(SV3_1aPpParser::Ifndef_directive_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitIfndef_directive_in_macro_body(SV3_1aPpParser::Ifndef_directive_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slIfndef_directive_in_macro_body); }
  virtual void enterElsif_directive(SV3_1aPpParser::Elsif_directiveContext * /*ctx*/) override ;
  virtual void exitElsif_directive(SV3_1aPpParser::Elsif_directiveContext * ctx) override { addVObject (ctx, VObjectType::slElsif_directive); }
  virtual void enterElsif_directive_in_macro_body(SV3_1aPpParser::Elsif_directive_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitElsif_directive_in_macro_body(SV3_1aPpParser::Elsif_directive_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slElsif_directive_in_macro_body); }
  virtual void enterElseif_directive(SV3_1aPpParser::Elseif_directiveContext * /*ctx*/) override ;
  virtual void exitElseif_directive(SV3_1aPpParser::Elseif_directiveContext * ctx) override { addVObject (ctx, VObjectType::slElseif_directive); }
  virtual void enterElseif_directive_in_macro_body(SV3_1aPpParser::Elseif_directive_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitElseif_directive_in_macro_body(SV3_1aPpParser::Elseif_directive_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slElseif_directive_in_macro_body); }
  virtual void enterElse_directive(SV3_1aPpParser::Else_directiveContext * /*ctx*/) override ;
  virtual void exitElse_directive(SV3_1aPpParser::Else_directiveContext * ctx) override { addVObject (ctx, VObjectType::slElse_directive); }
  virtual void enterEndif_directive(SV3_1aPpParser::Endif_directiveContext * /*ctx*/) override ;
  virtual void exitEndif_directive(SV3_1aPpParser::Endif_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEndif_directive); }
  virtual void enterResetall_directive(SV3_1aPpParser::Resetall_directiveContext * /*ctx*/) override ;
  virtual void exitResetall_directive(SV3_1aPpParser::Resetall_directiveContext * ctx) override { addVObject (ctx, VObjectType::slResetall_directive); }
  virtual void enterBegin_keywords_directive(SV3_1aPpParser::Begin_keywords_directiveContext * /*ctx*/) override ;
  virtual void exitBegin_keywords_directive(SV3_1aPpParser::Begin_keywords_directiveContext * ctx) override { addVObject (ctx, VObjectType::slBegin_keywords_directive); }
  virtual void enterEnd_keywords_directive(SV3_1aPpParser::End_keywords_directiveContext * /*ctx*/) override ;
  virtual void exitEnd_keywords_directive(SV3_1aPpParser::End_keywords_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEnd_keywords_directive); }
  virtual void enterPragma_directive(SV3_1aPpParser::Pragma_directiveContext * /*ctx*/) override ;
  virtual void exitPragma_directive(SV3_1aPpParser::Pragma_directiveContext * /*ctx*/) override ;
  virtual void enterCelldefine_directive(SV3_1aPpParser::Celldefine_directiveContext * /*ctx*/) override ;
  virtual void exitCelldefine_directive(SV3_1aPpParser::Celldefine_directiveContext * ctx) override { addVObject (ctx, VObjectType::slCelldefine_directive); }
  virtual void enterEndcelldefine_directive(SV3_1aPpParser::Endcelldefine_directiveContext * /*ctx*/) override ;
  virtual void exitEndcelldefine_directive(SV3_1aPpParser::Endcelldefine_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEndcelldefine_directive); }
  virtual void enterProtect_directive(SV3_1aPpParser::Protect_directiveContext * /*ctx*/) override ;
  virtual void exitProtect_directive(SV3_1aPpParser::Protect_directiveContext * ctx) override { addVObject (ctx, VObjectType::slProtect_directive); }
  virtual void enterEndprotect_directive(SV3_1aPpParser::Endprotect_directiveContext * /*ctx*/) override ;
  virtual void exitEndprotect_directive(SV3_1aPpParser::Endprotect_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEndprotect_directive); }
  virtual void enterProtected_directive(SV3_1aPpParser::Protected_directiveContext * /*ctx*/) override ;
  virtual void exitProtected_directive(SV3_1aPpParser::Protected_directiveContext * ctx) override { addVObject (ctx, VObjectType::slProtected_directive); }
  virtual void enterEndprotected_directive(SV3_1aPpParser::Endprotected_directiveContext * /*ctx*/) override ;
  virtual void exitEndprotected_directive(SV3_1aPpParser::Endprotected_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEndprotected_directive); }
  virtual void enterExpand_vectornets_directive(SV3_1aPpParser::Expand_vectornets_directiveContext * /*ctx*/) override ;
  virtual void exitExpand_vectornets_directive(SV3_1aPpParser::Expand_vectornets_directiveContext * ctx) override { addVObject (ctx, VObjectType::slExpand_vectornets_directive); }
  virtual void enterNoexpand_vectornets_directive(SV3_1aPpParser::Noexpand_vectornets_directiveContext * /*ctx*/) override ;
  virtual void exitNoexpand_vectornets_directive(SV3_1aPpParser::Noexpand_vectornets_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNoexpand_vectornets_directive); }
  virtual void enterAutoexpand_vectornets_directive(SV3_1aPpParser::Autoexpand_vectornets_directiveContext * /*ctx*/) override ;
  virtual void exitAutoexpand_vectornets_directive(SV3_1aPpParser::Autoexpand_vectornets_directiveContext * ctx) override { addVObject (ctx, VObjectType::slAutoexpand_vectornets_directive); }
  virtual void enterUselib_directive(SV3_1aPpParser::Uselib_directiveContext * /*ctx*/) override ;
  virtual void exitUselib_directive(SV3_1aPpParser::Uselib_directiveContext * ctx) override { addVObject (ctx, VObjectType::slUselib_directive); }
  virtual void enterDisable_portfaults_directive(SV3_1aPpParser::Disable_portfaults_directiveContext * /*ctx*/) override ;
  virtual void exitDisable_portfaults_directive(SV3_1aPpParser::Disable_portfaults_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDisable_portfaults_directive); }
  virtual void enterEnable_portfaults_directive(SV3_1aPpParser::Enable_portfaults_directiveContext * /*ctx*/) override ;
  virtual void exitEnable_portfaults_directive(SV3_1aPpParser::Enable_portfaults_directiveContext * ctx) override { addVObject (ctx, VObjectType::slEnable_portfaults_directive); }
  virtual void enterNosuppress_faults_directive(SV3_1aPpParser::Nosuppress_faults_directiveContext * /*ctx*/) override ;
  virtual void exitNosuppress_faults_directive(SV3_1aPpParser::Nosuppress_faults_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNosuppress_faults_directive); }
  virtual void enterSuppress_faults_directive(SV3_1aPpParser::Suppress_faults_directiveContext * /*ctx*/) override ;
  virtual void exitSuppress_faults_directive(SV3_1aPpParser::Suppress_faults_directiveContext * ctx) override { addVObject (ctx, VObjectType::slSuppress_faults_directive); }
  virtual void enterSigned_directive(SV3_1aPpParser::Signed_directiveContext * /*ctx*/) override ;
  virtual void exitSigned_directive(SV3_1aPpParser::Signed_directiveContext * ctx) override { addVObject (ctx, VObjectType::slSigned_directive); }
  virtual void enterUnsigned_directive(SV3_1aPpParser::Unsigned_directiveContext * /*ctx*/) override ;
  virtual void exitUnsigned_directive(SV3_1aPpParser::Unsigned_directiveContext * ctx) override { addVObject (ctx, VObjectType::slUnsigned_directive); }
  virtual void enterRemove_gatename_directive(SV3_1aPpParser::Remove_gatename_directiveContext * /*ctx*/) override ;
  virtual void exitRemove_gatename_directive(SV3_1aPpParser::Remove_gatename_directiveContext * ctx) override { addVObject (ctx, VObjectType::slRemove_gatename_directive); }
  virtual void enterNoremove_gatenames_directive(SV3_1aPpParser::Noremove_gatenames_directiveContext * /*ctx*/) override ;
  virtual void exitNoremove_gatenames_directive(SV3_1aPpParser::Noremove_gatenames_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNoremove_gatenames_directive); }
  virtual void enterRemove_netname_directive(SV3_1aPpParser::Remove_netname_directiveContext * /*ctx*/) override ;
  virtual void exitRemove_netname_directive(SV3_1aPpParser::Remove_netname_directiveContext * ctx) override { addVObject (ctx, VObjectType::slRemove_netname_directive); }
  virtual void enterNoremove_netnames_directive(SV3_1aPpParser::Noremove_netnames_directiveContext * /*ctx*/) override ;
  virtual void exitNoremove_netnames_directive(SV3_1aPpParser::Noremove_netnames_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNoremove_netnames_directive); }
  virtual void enterAccelerate_directive(SV3_1aPpParser::Accelerate_directiveContext * /*ctx*/) override ;
  virtual void exitAccelerate_directive(SV3_1aPpParser::Accelerate_directiveContext * ctx) override { addVObject (ctx, VObjectType::slAccelerate_directive); }
  virtual void enterNoaccelerate_directive(SV3_1aPpParser::Noaccelerate_directiveContext * /*ctx*/) override ;
  virtual void exitNoaccelerate_directive(SV3_1aPpParser::Noaccelerate_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNoaccelerate_directive); }
  virtual void enterDefault_trireg_strenght_directive(SV3_1aPpParser::Default_trireg_strenght_directiveContext * /*ctx*/) override ;
  virtual void exitDefault_trireg_strenght_directive(SV3_1aPpParser::Default_trireg_strenght_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDefault_trireg_strenght_directive); }
  virtual void enterDefault_decay_time_directive(SV3_1aPpParser::Default_decay_time_directiveContext * /*ctx*/) override ;
  virtual void exitDefault_decay_time_directive(SV3_1aPpParser::Default_decay_time_directiveContext * /*ctx*/) override ;
  virtual void enterUnconnected_drive_directive(SV3_1aPpParser::Unconnected_drive_directiveContext * /*ctx*/) override ;
  virtual void exitUnconnected_drive_directive(SV3_1aPpParser::Unconnected_drive_directiveContext * ctx) override { addVObject (ctx, VObjectType::slUnconnected_drive_directive); }
  virtual void enterNounconnected_drive_directive(SV3_1aPpParser::Nounconnected_drive_directiveContext * /*ctx*/) override ;
  virtual void exitNounconnected_drive_directive(SV3_1aPpParser::Nounconnected_drive_directiveContext * ctx) override { addVObject (ctx, VObjectType::slNounconnected_drive_directive); }
  virtual void enterDelay_mode_distributed_directive(SV3_1aPpParser::Delay_mode_distributed_directiveContext * /*ctx*/) override ;
  virtual void exitDelay_mode_distributed_directive(SV3_1aPpParser::Delay_mode_distributed_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDelay_mode_distributed_directive); }
  virtual void enterDelay_mode_path_directive(SV3_1aPpParser::Delay_mode_path_directiveContext * /*ctx*/) override ;
  virtual void exitDelay_mode_path_directive(SV3_1aPpParser::Delay_mode_path_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDelay_mode_path_directive); }
  virtual void enterDelay_mode_unit_directive(SV3_1aPpParser::Delay_mode_unit_directiveContext * /*ctx*/) override ;
  virtual void exitDelay_mode_unit_directive(SV3_1aPpParser::Delay_mode_unit_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDelay_mode_unit_directive); }
  virtual void enterDelay_mode_zero_directive(SV3_1aPpParser::Delay_mode_zero_directiveContext * /*ctx*/) override ;
  virtual void exitDelay_mode_zero_directive(SV3_1aPpParser::Delay_mode_zero_directiveContext * ctx) override { addVObject (ctx, VObjectType::slDelay_mode_zero_directive); }
  virtual void enterUndefineall_directive(SV3_1aPpParser::Undefineall_directiveContext * /*ctx*/) override ;
  virtual void exitUndefineall_directive(SV3_1aPpParser::Undefineall_directiveContext * ctx) override { addVObject (ctx, VObjectType::slUndefineall_directive); }
  virtual void enterModule(SV3_1aPpParser::ModuleContext * /*ctx*/) override ;
  virtual void exitModule(SV3_1aPpParser::ModuleContext * ctx) override { addVObject (ctx, VObjectType::slModule); }
  virtual void enterEndmodule(SV3_1aPpParser::EndmoduleContext * /*ctx*/) override ;
  virtual void exitEndmodule(SV3_1aPpParser::EndmoduleContext * ctx) override { addVObject (ctx, VObjectType::slEndmodule); }
  virtual void enterSv_interface(SV3_1aPpParser::Sv_interfaceContext * /*ctx*/) override ;
  virtual void exitSv_interface(SV3_1aPpParser::Sv_interfaceContext * ctx) override { addVObject (ctx, VObjectType::slSv_interface); }
  virtual void enterEndinterface(SV3_1aPpParser::EndinterfaceContext * /*ctx*/) override ;
  virtual void exitEndinterface(SV3_1aPpParser::EndinterfaceContext * ctx) override { addVObject (ctx, VObjectType::slEndinterface); }
  virtual void enterProgram(SV3_1aPpParser::ProgramContext * /*ctx*/) override ;
  virtual void exitProgram(SV3_1aPpParser::ProgramContext * ctx) override { addVObject (ctx, VObjectType::slProgram); }
  virtual void enterEndprogram(SV3_1aPpParser::EndprogramContext * /*ctx*/) override ;
  virtual void exitEndprogram(SV3_1aPpParser::EndprogramContext * ctx) override { addVObject (ctx, VObjectType::slEndprogram); }
  virtual void enterPrimitive(SV3_1aPpParser::PrimitiveContext * /*ctx*/) override ;
  virtual void exitPrimitive(SV3_1aPpParser::PrimitiveContext * ctx) override { addVObject (ctx, VObjectType::slPrimitive); }
  virtual void enterEndprimitive(SV3_1aPpParser::EndprimitiveContext * /*ctx*/) override ;
  virtual void exitEndprimitive(SV3_1aPpParser::EndprimitiveContext * ctx) override { addVObject (ctx, VObjectType::slEndprimitive); }
  virtual void enterSv_package(SV3_1aPpParser::Sv_packageContext * /*ctx*/) override ;
  virtual void exitSv_package(SV3_1aPpParser::Sv_packageContext * ctx) override { addVObject (ctx, VObjectType::slSv_package); }
  virtual void enterEndpackage(SV3_1aPpParser::EndpackageContext * /*ctx*/) override ;
  virtual void exitEndpackage(SV3_1aPpParser::EndpackageContext * ctx) override { addVObject (ctx, VObjectType::slEndpackage); }
  virtual void enterChecker(SV3_1aPpParser::CheckerContext * /*ctx*/) override ;
  virtual void exitChecker(SV3_1aPpParser::CheckerContext * ctx) override { addVObject (ctx, VObjectType::slChecker); }
  virtual void enterEndchecker(SV3_1aPpParser::EndcheckerContext * /*ctx*/) override ;
  virtual void exitEndchecker(SV3_1aPpParser::EndcheckerContext * ctx) override { addVObject (ctx, VObjectType::slEndchecker); }
  virtual void enterConfig(SV3_1aPpParser::ConfigContext * /*ctx*/) override ;
  virtual void exitConfig(SV3_1aPpParser::ConfigContext * ctx) override { addVObject (ctx, VObjectType::slConfig); }
  virtual void enterEndconfig(SV3_1aPpParser::EndconfigContext * /*ctx*/) override ;
  virtual void exitEndconfig(SV3_1aPpParser::EndconfigContext * ctx) override { addVObject (ctx, VObjectType::slEndconfig); }
  virtual void enterDefine_directive(SV3_1aPpParser::Define_directiveContext * /*ctx*/) override ;
  virtual void exitDefine_directive(SV3_1aPpParser::Define_directiveContext * /*ctx*/) override ;
  virtual void enterMultiline_no_args_macro_definition(SV3_1aPpParser::Multiline_no_args_macro_definitionContext * /*ctx*/) override ;
  virtual void exitMultiline_no_args_macro_definition(SV3_1aPpParser::Multiline_no_args_macro_definitionContext * /*ctx*/) override ;
  virtual void enterMultiline_args_macro_definition(SV3_1aPpParser::Multiline_args_macro_definitionContext * /*ctx*/) override ;
  virtual void exitMultiline_args_macro_definition(SV3_1aPpParser::Multiline_args_macro_definitionContext * /*ctx*/) override ;
  virtual void enterSimple_no_args_macro_definition(SV3_1aPpParser::Simple_no_args_macro_definitionContext * /*ctx*/) override ;
  virtual void exitSimple_no_args_macro_definition(SV3_1aPpParser::Simple_no_args_macro_definitionContext * /*ctx*/) override ;
  virtual void enterSimple_args_macro_definition(SV3_1aPpParser::Simple_args_macro_definitionContext * /*ctx*/) override ;
  virtual void exitSimple_args_macro_definition(SV3_1aPpParser::Simple_args_macro_definitionContext * /*ctx*/) override ;
  virtual void enterIdentifier_in_macro_body(SV3_1aPpParser::Identifier_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitIdentifier_in_macro_body(SV3_1aPpParser::Identifier_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slIdentifier_in_macro_body); }
  virtual void enterSimple_no_args_macro_definition_in_macro_body(SV3_1aPpParser::Simple_no_args_macro_definition_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitSimple_no_args_macro_definition_in_macro_body(SV3_1aPpParser::Simple_no_args_macro_definition_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slSimple_no_args_macro_definition_in_macro_body); }
  virtual void enterSimple_args_macro_definition_in_macro_body(SV3_1aPpParser::Simple_args_macro_definition_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitSimple_args_macro_definition_in_macro_body(SV3_1aPpParser::Simple_args_macro_definition_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slSimple_args_macro_definition_in_macro_body); }
  virtual void enterDirective_in_macro(SV3_1aPpParser::Directive_in_macroContext * /*ctx*/) override { }
  virtual void exitDirective_in_macro(SV3_1aPpParser::Directive_in_macroContext * ctx) override { addVObject (ctx, VObjectType::slDirective_in_macro); }
  virtual void enterMacro_arguments(SV3_1aPpParser::Macro_argumentsContext * /*ctx*/) override { }
  virtual void exitMacro_arguments(SV3_1aPpParser::Macro_argumentsContext * ctx) override { addVObject (ctx, VObjectType::slMacro_arguments); }
  virtual void enterEscaped_macro_definition_body(SV3_1aPpParser::Escaped_macro_definition_bodyContext * /*ctx*/) override { }
  virtual void exitEscaped_macro_definition_body(SV3_1aPpParser::Escaped_macro_definition_bodyContext * /*ctx*/) override ;
  virtual void enterEscaped_macro_definition_body_alt1(SV3_1aPpParser::Escaped_macro_definition_body_alt1Context * /*ctx*/) override { }
  virtual void exitEscaped_macro_definition_body_alt1(SV3_1aPpParser::Escaped_macro_definition_body_alt1Context * ctx) override { addVObject (ctx, VObjectType::slEscaped_macro_definition_body_alt1); }
  virtual void enterEscaped_macro_definition_body_alt2(SV3_1aPpParser::Escaped_macro_definition_body_alt2Context * /*ctx*/) override { }
  virtual void exitEscaped_macro_definition_body_alt2(SV3_1aPpParser::Escaped_macro_definition_body_alt2Context * ctx) override { addVObject (ctx, VObjectType::slEscaped_macro_definition_body_alt2); }
  virtual void enterSimple_macro_definition_body(SV3_1aPpParser::Simple_macro_definition_bodyContext * /*ctx*/) override { }
  virtual void exitSimple_macro_definition_body(SV3_1aPpParser::Simple_macro_definition_bodyContext * /*ctx*/) override ;
  virtual void enterSimple_macro_definition_body_in_macro_body(SV3_1aPpParser::Simple_macro_definition_body_in_macro_bodyContext * /*ctx*/) override { }
  virtual void exitSimple_macro_definition_body_in_macro_body(SV3_1aPpParser::Simple_macro_definition_body_in_macro_bodyContext * ctx) override { addVObject (ctx, VObjectType::slSimple_macro_definition_body_in_macro_body); }
  virtual void enterPragma_expression(SV3_1aPpParser::Pragma_expressionContext * /*ctx*/) override { }
  virtual void exitPragma_expression(SV3_1aPpParser::Pragma_expressionContext * /*ctx*/) override ;
  virtual void enterMacro_arg(SV3_1aPpParser::Macro_argContext * /*ctx*/) override { }
  virtual void exitMacro_arg(SV3_1aPpParser::Macro_argContext * /*ctx*/) override ;
  virtual void enterPaired_parens(SV3_1aPpParser::Paired_parensContext * /*ctx*/) override { }
  virtual void exitPaired_parens(SV3_1aPpParser::Paired_parensContext * ctx) override { addVObject (ctx, VObjectType::slPaired_parens); }
  virtual void enterText_blob(SV3_1aPpParser::Text_blobContext * /*ctx*/) override ;
  virtual void exitText_blob(SV3_1aPpParser::Text_blobContext * /*ctx*/) override ;
  virtual void enterString(SV3_1aPpParser::StringContext * /*ctx*/) override ;
  virtual void exitString(SV3_1aPpParser::StringContext * ctx) override { addVObject (ctx, VObjectType::slString); }
  virtual void enterEscaped_identifier(SV3_1aPpParser::Escaped_identifierContext * /*ctx*/) override ;
  virtual void exitEscaped_identifier(SV3_1aPpParser::Escaped_identifierContext * ctx) override { addVObject (ctx, VObjectType::slEscaped_identifier); }
  virtual void enterDefault_value(SV3_1aPpParser::Default_valueContext * /*ctx*/) override { }
  virtual void exitDefault_value(SV3_1aPpParser::Default_valueContext * /*ctx*/) override ;
  virtual void enterString_blob(SV3_1aPpParser::String_blobContext * /*ctx*/) override { }
  virtual void exitString_blob(SV3_1aPpParser::String_blobContext * /*ctx*/) override ;
  virtual void enterEveryRule(antlr4::ParserRuleContext * /*ctx*/) override ;
  virtual void exitEveryRule(antlr4::ParserRuleContext * /*ctx*/) override ;
  virtual void visitTerminal(antlr4::tree::TerminalNode * /*node*/) override ;
  virtual void visitErrorNode(antlr4::tree::ErrorNode * /*node*/) override ;
    };
};

#endif /* SV3_1APPTREESHAPELISTENER_H */

