#!/bin/bash
# Script used to have Surelog as a stand-in replacement for Verilator
if [ $1 == "--version" ]
then echo "Verilator 4.104 2020-11-14 rev v4.104"
exit 0
fi 
/home/alain/Surelog/build/bin/surelog -DVERILATOR=1 -parse -verbose -elabuhdm -d coveruhdm $@
