## 
## -------------------------------------------------------------
##    Copyright 2008 Mentor Graphics Corporation
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 


VMM_HOME = ../../../..
include $(VMM_HOME)/sv/examples/Makefile

TESTS = test_simple test_ovm_sb test_ovm_with_vmm_env test_ovm_env_wrap test_ovm_env

run: $(addsuffix .log, $(TESTS))

APB_HOME = apb


%.log: %.sv %.$(WORK) $(VMM_DPI)
	$(VLOG) +incdir+$(APB_HOME)+. +vmm_log_default=trace \
	    -work $*.work $*.sv tb_top.sv
	$(VSIM) -lib $*.work tb_top $* -l $@ +vmm_log_default=trace 
	@-$(SELF_CHECK_CMD)
